export const typeActions = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  SET_CATEGORY: "SET_CATEGORY",
  ADD_TO_CART: "ADD_TO_CART",
  EDIT_ITEM_QUANTITY: "EDIT_ITEM_QUANTITY",
  REMOVE_CART_ITEM: "REMOVE_CART_ITEM",
}